backend:
  name: github
  repo: cescoferraro/fruki
  branch: main

media_folder: static/assets
public_folder: /assets
collections:
  - name: marca
    label: Marca
    folder: content/marca
    create: true
    public_folder: ../../static/assets/marca
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Nome }
      - { name: description, label: Descrição, required: false }
      - { name: logo, label: Imagem de produto, widget: image, media_folder: ../../static/assets/marca }
      - { name: background, label: Background da Marca, widget: image }
      - { name: color , label: Color, required: true, widget: color }
  - name: produto
    label: Produto
    folder: content/produto
    create: true
    public_folder: ../../static/assets/produto
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Nome }
      - { name: description, label: Descrição, required: false }
      - { name: image, label: Imagem de produto, widget: image, media_folder: ../../static/assets/produto }
      - { name: color , label: Color, required: true, widget: color }
      - label: "Marca"
        name: "brand"
        widget: "relation"
        collection: "marca"
        multiple: false
        searchFields: [ "name" ]
        valueField: "path"
        displayFields: [ "name" ]
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: title, label: Título }
      - { name: url, label: Url }
      - { name: description, label: Descrição, required: false }
      - { name: "body", label: "Conteúdo do blog post", widget: "markdown" }
      - { name: author, label: Autor do post, required: false }
      - { name: about, label: Sobre o autor, required: false }
  - name: certificate
    label: Certificados
    folder: content/certificate
    create: true
    public_folder: ../../static/assets/certificate
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Nome }
      - { name: color , label: Color, required: true, widget: color }
      - { name: image, label: Imagem de destaque, widget: image, media_folder: ../../static/assets/certificate }
  - name: faq
    label: FAQS
    folder: content/faq
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: question, label: Pergunta }
      - { name: "body", label: "Conteúdo da Iniciativa", widget: "markdown" }
  - name: timeline
    label: Timeline
    folder: content/timeline
    create: true
    public_folder: ../../static/assets/timeline
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: year, label: Ano }
      - { name: description, label: Descrição, required: false }
      - { name: image, label: Imagem de destaque, widget: image, media_folder: ../../static/assets/timeline }
  - name: initiative
    label: Initiatives
    folder: content/iniciativas
    create: true
    public_folder: ../../static/assets/iniciativas
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: title, label: Título }
      - { name: description, label: Descrição, required: false }
      - { name: "body", label: "Conteúdo da Iniciativa", widget: "markdown" }
      - { name: color , label: Color, required: true, widget: color }
      - { name: image, label: Imagem de destaque, widget: image, media_folder: ../../static/assets/iniciativas }
  - name: location
    label: Locations
    folder: content/location
    create: true
    public_folder: ../../static/assets/location
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: title, label: Título }
      - { name: endereco, label: Endereço }
      - { name: local, label: Localização }
      - { name: image, label: Imagem de destaque, widget: image, media_folder: ../../static/assets/location }
  - name: tag
    label: Tag
    folder: content/tag
    create: true
    fields:
      - { name: tag_name, label: Tag, widget: string }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: content/home.yml
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Caption, name: caption, widget: string }
      - label: Privacidade
        name: privacy
        file: content/privacy.md
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Title, name: title, widget: string }
          - { name: body, label: Conteúdo do privacy, widget: markdown }
  - name: banners
    label: Banner
    folder: content/banner
    create: true
    public_folder: ../../static/assets/banner
    fields:
      - { name: path, label: Path }
      - { name: date, label: Data, widget: date }
      - { name: name, label: Nome }
      - { name: link, label: Link }
      - { name: description, label: Descrição, required: false }
      - { name: desktop, label: Desktop, widget: image, media_folder: ../../static/assets/banner }
      - { name: mobile, label: Mobile, widget: image, media_folder: ../../static/assets/banner }
