name: Fruki Deploy
on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "francescoaferraro@gmail.com"
          git config --global user.name "cescoferraro"
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
           git config --global user.email "francescoaferraro@gmail.com"
           git config --global user.name "cescoferraro"
           - name: Checkout
             uses: actions/checkout@v3
           - uses: actions/setup-node@v3
             with:
               node-version: 18
      - name: Install dependencies
        run: |
           npm install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cescoferraro/fruki-api:latest
      - name: Run Docker CMD
        uses: appleboy/ssh-action@master
        with:
          host: 170.187.155.62
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker stop fruki-api && docker rm fruki-api
            docker pull cescoferraro/fruki-api:latest
            docker run -itd --name fruki-api --env "VIRTUAL_HOST=api.fruki.cescoferraro.com" --env "VIRTUAL_PORT=3333" --env "LETSENCRYPT_HOST=api.fruki.cescoferraro.com" --env "LETSENCRYPT_EMAIL=francescoaferraro@gmail.com" --env DB_HOST="172.17.0.1" cescoferraro/fruki-api